name: Pre-Release Version Bump

on:
  push:
    branches:
      - prod

jobs:
  version:
    runs-on: ubuntu-latest
    if: '!startsWith(github.event.head_commit.message, "[PRE-RELEASE]")'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RISEFUNDS_BENEDICT_PAT }}
      - run: git config --global user.name 'derickben'
      - run: git config --global user.email 'benedictuyioghosas@gmail.com'
      - run: npm version prerelease --preid=alpha -m "[PRE-RELEASE] %s"
      - run: git push --follow-tags
